### ISSUE TITLE
Resetting AudioSrv on Windows 11 freezes Retroarch

### ISSUE THREAD

**Issue by ghost** [libretro/swanstation#117]
Unsure if this is a SwanStation issue or an RA issue, but Stopping then Starting (resetting) Windows 11's AudioSrv via these two commands freezes RA indefinitely:

net stop audiosrv
net start audiosrv

Happens without fail.

(I have to run these commands often because for some reason on Win 11 my audio stops several times seemingly randomly after a wake cycle).

**Comment by DarthMew** [comment]
You might want to check your computers audio driver first, seeing as you have to restart AudioSrv with such a frequency.

In any case, did you try to restart AudioSrv with any other cores running?

**Comment by ghost** [comment]
I have not, but I will try that now.

**Comment by Apocalypse612** [comment]
The issue persists, I'll repost this on the RA github. Sorry!

**Comment by ghost** [comment]
The issue persists, I'll repost this on the RA github. Sorry!
