### ISSUE TITLE
Problem with analog

### ISSUE THREAD

**Issue by hacls1** [libretro/swanstation#14]
There's something wrong with the analog, simply does not work properly. Looks that when you move the stick the registered digital value are the lowest possible. In DuckStation works fine.

**Comment by DarthMew** [comment]
> > > There's something wrong with the analog, simply does not work properly. In DuckStation works fine. Looks that when you move the stick the registered digital value are the lowest possible.
> > 
> > 
> > I had to set analog axis scale to 1.40 to be able to run at all angles with an xbox series x controller in Parasite eve. There should be more values available for the user to set it to. In standalone Duckstation a value 1.21 is enough for the same controller. 1.40 feels off.
> 
> Sorry, I remove the post to create a new topic for this issue...
> 
> I'm now using Razer Kishi on android, but with keyboard on PC or even with the default overlay gamepad from RA... All with the same problem...
> 
> I use the analog sense in 1.5 (for GameSir X2) or 1.3 when I use the PS4 controller or Razer Kishi from RetroArch Input options. I tried to change all the options from SwanStation as well including this "Analog Axis Scale" option 1.0 to 1.4... The problem continues...

Is the problem you're having that moving the analog stick moves as if you're moving by using the d-pad (I.E. full press)?
When you load the game, does it at any point indicate that the analog sticks have been enabled, because if not, the game in question might not natively enable analog mode on the DualShock, and will have to be either enabled manually by pressing L1+R1+L3+R3 at the same time, or by enabling "Controller X Force Analog Mode on Reset" and restarting the game.

**Comment by hacls1** [comment]
> > > > There's something wrong with the analog, simply does not work properly. In DuckStation works fine. Looks that when you move the stick the registered digital value are the lowest possible.
> > > 
> > > 
> > > I had to set analog axis scale to 1.40 to be able to run at all angles with an xbox series x controller in Parasite eve. There should be more values available for the user to set it to. In standalone Duckstation a value 1.21 is enough for the same controller. 1.40 feels off.
> > 
> > 
> > Sorry, I remove the post to create a new topic for this issue...
> > I'm now using Razer Kishi on android, but with keyboard on PC or even with the default overlay gamepad from RA... All with the same problem...
> > I use the analog sense in 1.5 (for GameSir X2) or 1.3 when I use the PS4 controller or Razer Kishi from RetroArch Input options. I tried to change all the options from SwanStation as well including this "Analog Axis Scale" option 1.0 to 1.4... The problem continues...
> 
> Is the problem you're having that moving the analog stick moves as if you're moving by using the d-pad (I.E. full press)? When you load the game, does it at any point indicate that the analog sticks have been enabled, because if not, the game in question might not natively enable analog mode on the DualShock, and will have to be either enabled manually by pressing L1+R1+L3+R3 at the same time, or by enabling "Controller X Force Analog Mode on Reset" and restarting the game.

Yeah.. this "Analog Mode on Reset" works... Thanks.

I tested in FF9.

But why? In others emulators I simply change to DualShock in Port 1 Controls>Device Type and it's like removing the controller from the PS1 and putting the DualShock on the console. Works on every emulator that way including DuckStation.

But, thanks anyway.
