### ISSUE TITLE
Feature Request: Internal Framerate Counter

### ISSUE THREAD

**Issue by brad86m** [libretro/swanstation#17]
Internal framerate counter similar to the one implemented within BeetlePSX. Would be incredibly useful for keeping an eye on frame rate whilst tweaking overclocking.

**Comment by DarthMew** [comment]
Added with https://github.com/libretro/swanstation/commit/0e53a5ac09a30d73d78b628f7e4954ebe5615801

**Comment by brad86m** [comment]
Hi there. The option has disappeared within Swanstation, and I'm not too sure why.

Mistake, or something else ?
