### ISSUE TITLE
Core Linear Filter Option Looks Wrong

### ISSUE THREAD

**Issue by Awakened0** [libretro/swanstation#19]
The core's Linear Filter option (enabled by default) looks off compared to RetroArch's Bilinear Filtering option under Settings, Video.

No Filter:
![No Filter1](https://user-images.githubusercontent.com/4565863/165229797-ea7d0e5d-2daa-49bd-8688-80610dff94a1.png)

Core Filter:
![Core Linear1](https://user-images.githubusercontent.com/4565863/165229850-b605d443-c19c-4430-84f8-df43a88c621f.png)

RetroArch Filter:
![Frontend Linear1](https://user-images.githubusercontent.com/4565863/165229917-ce971abe-d44b-45d5-afba-7c8e50c6f96c.png)

Tested in both hardware renderers at 1x resolution. Doesn't seem to work with the software renderer.

I would argue the option should be removed, since the frontend's filtering works well. Even if the core option is fixed, it should at least be off by default to match the frontend's filtering default.

**Comment by DarthMew** [comment]
Removed as unnecessary via https://github.com/libretro/swanstation/commit/46c1e16495a6ad1173a24294f14b6cfccf0b0cea

**Comment by Awakened0** [comment]
Thanks!
