### ISSUE TITLE
[Lakka] game override core options supported?

### ISSUE THREAD

**Issue by evbo** [libretro/swanstation#2]
Hi,

Please see similar issue and discussion here:
https://discord.com/channels/184109094070779904/392140187548909580/939637100251328533

Essentially there doesn't seem to appear any game specific "opt" file in Lakka when a game override is saved. This is an issue for both duck and swan station. According to the linked issue, this is a core problem and should be posted here

https://github.com/libretro/Lakka-LibreELEC/issues/1589

**Comment by DarthMew** [comment]
Weird, because core, content, and game overrides set through the overrides submenu, as well as core option overrides set through the options submenu create the necessary .opt and .cfg files just fine with RetroArch 1.10.0 on both Windows 10 and Android.

**Comment by evbo** [comment]
Thanks, and I should add I am running using Lakka 3.6 (latest)

**Comment by DarthMew** [comment]
Just tried it out with a live image of the latest Lakka 3.6, and I can still seem to save override .cfg and .opt files just fine.
Could you perhaps provide me with a log, so I can better see what exactly might be happening when you try to save an override file?

**Comment by DarthMew** [comment]
Closing this because, as it turns out, this all seems to be due to user confusion regarding how per-game core options and per-game overrides actually works, which @Sanaki perfectly explains [here](https://github.com/libretro/Lakka-LibreELEC/issues/1589#issuecomment-1037477131).
