### ISSUE TITLE
OpenGL ES option?

### ISSUE THREAD

**Issue by dmanlfc** [libretro/swanstation#22]
Is there an OpenGLES compilation option?
If RA is compiled against OpenGLES for SBC's then libretro swanstation doesn't work (only using vulkan).
It seems swanstation only has OpenGL in compilation.

**Comment by DarthMew** [comment]
SwanStation does support OpenGLES though, at least as far as I can test it out on an Android smartphone.
Happen to know what version of OpenGLES your SBC supports?

**Comment by dmanlfc** [comment]
Hi @DarthMew this is for SBC's running Linux. How should we build in the scenario when OpenGLES is the only option. Most are 3.x

**Comment by DarthMew** [comment]
It should build including OpenGLES without any sort of special flags set, as the compiled core should test whenever or not the system it's running on has OpenGLES or not before defaulting to OpenGL.
And OpenGLES 3.x IIRC should also be supported just fine.

Also, make sure that, when you are running SwanStation, you have the renderer option set to either "Auto" or "OpenGL"(bit confusing, but includes GLES), with the former also having RetroArch's renderer set to the appropriate GL renderer.

**Comment by dmanlfc** [comment]
Unfortunately RA sees it as an OpenGL core not GLES. 
Other libretro cores allow you set this explicitly. i.e. USE_OPENGL or USE_GLES
We cross compile cores across multiple platforms.

**Comment by dmanlfc** [comment]
I found the problem, we were compiling RA with opengles 3.2 support.
I downgraded this back to 3.1 to align with swanstation, which resolves the problem.
