### ISSUE TITLE
retroarch crashes when loading save states

### ISSUE THREAD

**Issue by illcutyouin** [libretro/swanstation#24]
the crashes don't happen everytime it feels random here is the log, not sure how to upload the save state says the file type is not supported.

[INFO] RetroArch 1.10.3 (Git 1ff91fe)
[INFO] === Build =======================================
[INFO] CPU Model Name: 12th Gen Intel(R) Core(TM) i9-12900K
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Apr 15 2022
[INFO] Version: 1.10.3
[INFO] Git: 1ff91fe
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[INFO] [GL]: Found GL context: "wgl".
[INFO] [GL]: Detecting screen resolution: 1920x1080.
[INFO] [WGL]: Extensions: WGL_ARB_buffer_region WGL_ARB_create_context WGL_ARB_create_context_no_error WGL_ARB_create_context_profile WGL_ARB_create_context_robustness WGL_ARB_context_flush_control WGL_ARB_extensions_string WGL_ARB_make_current_read WGL_ARB_mult[INFO] [WGL]: Adaptive VSync supported.
[INFO] [GL]: Vendor: NVIDIA Corporation, Renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2.
[INFO] [GL]: Version: 4.6.0 NVIDIA 512.95.
[INFO] [GL]: Using resolution 1920x1080.
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [XInput]: Found XInput v1.4.
[WARN] [DInput]: Strong rumble unavailable.
[WARN] [DInput]: Weak rumble unavailable.
[INFO] [Joypad]: Found joypad driver: "dinput".
[INFO] [Font]: Using font rendering backend: "freetype".
[INFO] [Video]: Found display server: "win32".
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "gl".
[INFO] [SRAM]: SRAM will not be saved.
[INFO] [Playlist]: Loading history file: "C:\RetroArch-Win64\content_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\RetroArch-Win64\content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\RetroArch-Win64\content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\RetroArch-Win64\content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "C:\RetroArch-Win64\content_favorites.lpl".
[INFO] [Core]: Using content: "C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] RetroArch 1.10.3 (Git 1ff91fe)
[INFO] === Build =======================================
[INFO] CPU Model Name: 12th Gen Intel(R) Core(TM) i9-12900K
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Apr 15 2022
[INFO] Version: 1.10.3
[INFO] Git: 1ff91fe
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Core]: Loading dynamic libretro core from: "C:\RetroArch-Win64\cores\swanstation_libretro.dll"
[INFO] [Overrides]: No core-specific overrides found at "C:\RetroArch-Win64\config\SwanStation\SwanStation.cfg".
[INFO] [Overrides]: No content-dir-specific overrides found at "C:\RetroArch-Win64\config\SwanStation\\Roms.cfg".
[INFO] [Overrides]: No game-specific overrides found at "C:\RetroArch-Win64\config\SwanStation\Lunar - Silver Star Story Complete (USA) (Disc 1).cfg".
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Remaps]: Remap directory: "C:\RetroArch-Win64\config\remaps".
[INFO] [Remaps]: Core-specific remap found at "C:\RetroArch-Win64\config\remaps\SwanStation\SwanStation.rmp".
[INFO] [Overrides]: Redirecting save file to "C:\RetroArch-Win64\saves\Lunar - Silver Star Story Complete (USA) (Disc 1).srm".
[INFO] [Overrides]: Redirecting save state to "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state".
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[INFO] [Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [Environ]: GET_MESSAGE_INTERFACE_VERSION.
[libretro INFO] [LibretroHostInterface] Port 1 = Digital Controller (Gamepad)
[libretro INFO] [LibretroHostInterface] Port 2 = None
[libretro INFO] [LibretroHostInterface] Port 3 = None
[libretro INFO] [LibretroHostInterface] Port 4 = None
[libretro INFO] [LibretroHostInterface] Port 5 = None
[libretro INFO] [LibretroHostInterface] Port 6 = None
[libretro INFO] [LibretroHostInterface] Port 7 = None
[libretro INFO] [LibretroHostInterface] Port 8 = None
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[libretro INFO] [Main] retro_load_game(C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue)
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[libretro INFO] [HostInterface] Boot Filename: C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[libretro INFO] [HostInterface] Creating 'Cubeb' audio stream, sample rate = 44100, channels = 2, buffer size = 2048
[libretro INFO] [System] Loading CD image 'C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue'...
[libretro INFO] [System] Auto-detected console NTSC-U region for 'C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue' (region NTSC-U)
[libretro INFO] [System] Console Region: NTSC-U/C (US, Canada)
[INFO] [Environ]: SYSTEM_DIRECTORY: "C:\RetroArch-Win64\system".
[libretro INFO] [LibretroHostInterface] Running game changed: SLUS-00628 (Lunar - Silver Star Story Complete (USA) (Disc 1))
[libretro INFO] [Common::MemoryArena] File mapping name: duckstation_12140_00007FFA8BB3DBE0
[libretro INFO] [Bus] RAM is 2097152 bytes at 000000000A220000
[libretro INFO] [GPUBackend] GPU thread started.
[libretro INFO] [Bus] Fastmem base (software): 0000000010C03040
[libretro INFO] [CDROMAsyncReader] Read thread started with readahead of 8 sectors
[libretro INFO] [CDROM] Inserting new media, disc region: NTSC-U, console region: NTSC-U
[INFO] [Environ]: GET_PREFERRED_HW_RENDER, video driver name: gl.
[INFO] [Environ]: GET_PREFERRED_HW_RENDER - Context callback set to RETRO_HW_CONTEXT_OPENGL.
[libretro INFO] [LibretroHostInterface] Renderer = OpenGL
[libretro INFO] [LibretroHostInterface] Requesting hardware renderer context for OpenGL
[INFO] [Environ]: SET_HW_RENDER, context type: glcore.
[INFO] Requesting core OpenGL context (3.3).
[INFO] Reached end of SET_HW_RENDER.
[INFO] [RCHEEVOS]: Load started, hardcore not active
[INFO] [RCHEEVOS]: Using host: https://retroachievements.org
[INFO] [RCHEEVOS]: Found 7 potential consoles for cue file extension
[INFO] [RCHEEVOS]: Trying console 12
[INFO] [RCHEEVOS]: Opened Lunar - Silver Star Story Complete (USA) (Disc 1).cue
[INFO] [RCHEEVOS]: Found MODE2/2352 track 1 (first sector 0, sector size 2352, 0 pregap sectors)
[INFO] [RCHEEVOS]: Opened Lunar - Silver Star Story Complete (USA) (Disc 1) (Track 1).bin
[INFO] [RCHEEVOS]: Opened track 1 (sector size 2352)
[INFO] [RCHEEVOS]: Found SYSTEM.CNF at sector 246471
[INFO] [RCHEEVOS]: Looking for boot executable: SLUS_006.28
[INFO] [RCHEEVOS]: Found SLUS_006.28 at sector 246300
[INFO] [RCHEEVOS]: Hashing SLUS_006.28 title (11 bytes) and contents (350208 bytes) 
[INFO] [RCHEEVOS]: Generated hash f6fa4699dc9b8718d30b740329be18b3
[INFO] [RCHEEVOS]: Attempting to login Amakusa (with token)
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[libretro INFO] [LibretroHostInterface] base = 256x239, max = 1024x512, aspect ratio = 1.33, fps = 59.82
[INFO] [Audio]: Set audio input rate to: 44234.67 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[INFO] [Video]: Using HW render, glcore driver forced.
[INFO] [Video]: "glcore" saved as cached driver.
[INFO] [GLCore]: Found GL context: "wgl".
[INFO] [GLCore]: Detecting screen resolution: 1920x1080.
[INFO] [WGL]: Extensions: WGL_ARB_buffer_region WGL_ARB_create_context WGL_ARB_create_context_no_error WGL_ARB_create_context_profile WGL_ARB_create_context_robustness WGL_ARB_context_flush_control WGL_ARB_extensions_string WGL_ARB_make_current_read WGL_ARB_mult[INFO] [WGL]: Adaptive VSync supported.
[INFO] [GLCore]: Initializing HW render (1024x1024).
[INFO] [GLCore]: Max texture size: 32768 px, renderbuffer size: 32768 px.
[INFO] [GLCore]: Vendor: NVIDIA Corporation, Renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2.
[INFO] [GLCore]: Version: 4.6.0 NVIDIA 512.95.
[INFO] [GLCore]: Using resolution 1920x1080.
[WARN] [DInput]: Strong rumble unavailable.
[WARN] [DInput]: Weak rumble unavailable.
[INFO] [Joypad]: Found joypad driver: "dinput".
[INFO] [GLCore]: Loading stock shader.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [GLCore]: Not using frame history.
[INFO] [GLCore]: Not using framebuffer feedback.
[INFO] [Font]: Using font rendering backend: "freetype".
[INFO] [Video]: Found display server: "win32".
[libretro INFO] [LibretroHostInterface] Hardware context reset, type = 3
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[libretro INFO] [LibretroHostInterface] Shader cache directory: 'C:\RetroArch-Win64\saves\duckstation_cache\'
[libretro INFO] [GPUBackend] GPU thread stopped.
[libretro INFO] [GPU_HW_OpenGL] Max texture size: 32768x32768
[libretro INFO] [GPU_HW_OpenGL] Per-sample shading: supported
[libretro INFO] [GPU_HW_OpenGL] Max multisamples: 32
[libretro INFO] [GPU_HW_OpenGL] Uniform buffer offset alignment: 256
[libretro INFO] [GPU_HW_OpenGL] Max texel buffer size: 134217728
[libretro INFO] [GPU_HW] Resolution Scale: 1 (1024x512), maximum 32
[libretro INFO] [GPU_HW] Multisampling: 1x
[libretro INFO] [GPU_HW] Dithering: Enabled (Scaled)
[libretro INFO] [GPU_HW] Texture Filtering: Nearest-Neighbor
[libretro INFO] [GPU_HW] Dual-source blending: Supported
[libretro INFO] [GPU_HW] Using UV limits: NO
[libretro INFO] [GPU_HW] Depth buffer: NO
[libretro INFO] [GPU_HW] Downsampling: Disabled
[libretro INFO] [GPU_HW] Using software renderer for readbacks: NO
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[libretro INFO] [LibretroHostInterface] Shader cache directory: 'C:\RetroArch-Win64\saves\duckstation_cache\'
[libretro INFO] [GL::ShaderCache] 1 program binary formats supported by driver
[libretro INFO] [GL::ShaderCache] Read 126 entries from 'C:\RetroArch-Win64\saves\duckstation_cache\gl_programs.idx'
[libretro INFO] [ResetBatchVertexDepth] Resetting batch vertex depth
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "glcore".
[INFO] [Playlist]: Loading history file: "C:\RetroArch-Win64\content_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\RetroArch-Win64\content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\RetroArch-Win64\content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\RetroArch-Win64\content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "C:\RetroArch-Win64\content_favorites.lpl".
[libretro INFO] [LibretroHostInterface] Port 1 = Analog Controller (DualShock)
[libretro INFO] [LibretroHostInterface] Port 2 = Digital Controller (Gamepad)
[libretro INFO] [LibretroHostInterface] Port 3 = None
[libretro INFO] [LibretroHostInterface] Port 4 = None
[libretro INFO] [LibretroHostInterface] Port 5 = None
[libretro INFO] [LibretroHostInterface] Port 6 = None
[libretro INFO] [LibretroHostInterface] Port 7 = None
[libretro INFO] [LibretroHostInterface] Port 8 = None
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [RCHEEVOS]: Amakusa logged in successfully
[INFO] [RCHEEVOS]: Fetched user unlocks 11254
[INFO] [RCHEEVOS]: Fetched game data 11254
[INFO] [RCHEEVOS]: Fetched hardcore user unlocks 11254
[INFO] [RCHEEVOS]: Starting periodic rich presence update task for game 11254
[INFO] [RCHEEVOS]: Registered 0x10000 bytes of SYSTEM RAM at $000000 (offset 0x000000)
[INFO] [RCHEEVOS]: Registered 0x1F0000 bytes of SYSTEM RAM at $010000 (offset 0x010000)
[INFO] [RCHEEVOS]: Load finished
[INFO] [RCHEEVOS]: You have 36 of 107 achievements unlocked.
[INFO] [RCHEEVOS]: Started session for game 11254
[libretro WARN] [ExecuteCommand] CDROM Pause command while seeking from 224708 to 168 - jumping to seek target
[libretro INFO] [MemoryCard] Writing memory card sector 63
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553144 bytes.
[INFO] [State]: Saving state "RAM", 11553144 bytes.
[libretro INFO] [CDROM] Removing CD...
[libretro INFO] [System] Re-using same media 'C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue'
[libretro INFO] [System] Switched to subimage 0 in 'C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue'
[libretro INFO] [CDROM] Inserting new media, disc region: NTSC-U, console region: NTSC-U
[libretro INFO] [ResetBatchVertexDepth] Resetting batch vertex depth
[INFO] [RCHEEVOS]: Awarding achievement 159855: The Cranky, Stinky, Rude Genius (Meet Myght in his tower)
[INFO] [RCHEEVOS]: Awarded achievement 159855
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553144 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "RAM", 11553056 bytes.
[libretro INFO] [CDROM] Removing CD...
[libretro INFO] [System] Re-using same media 'C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue'
[libretro INFO] [System] Switched to subimage 0 in 'C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue'
[libretro INFO] [CDROM] Inserting new media, disc region: NTSC-U, console region: NTSC-U
[libretro INFO] [ResetBatchVertexDepth] Resetting batch vertex depth
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "RAM", 11553056 bytes.
[libretro INFO] [CDROM] Removing CD...
[libretro INFO] [System] Re-using same media 'C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue'
[libretro INFO] [System] Switched to subimage 0 in 'C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue'
[libretro INFO] [CDROM] Inserting new media, disc region: NTSC-U, console region: NTSC-U
[libretro INFO] [ResetBatchVertexDepth] Resetting batch vertex depth
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "RAM", 11553056 bytes.
[libretro INFO] [CDROM] Removing CD...
[libretro INFO] [System] Re-using same media 'C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue'
[libretro INFO] [System] Switched to subimage 0 in 'C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue'
[libretro INFO] [CDROM] Inserting new media, disc region: NTSC-U, console region: NTSC-U
[libretro INFO] [ResetBatchVertexDepth] Resetting batch vertex depth
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "RAM", 11553056 bytes.
[libretro INFO] [CDROM] Removing CD...
[libretro INFO] [System] Re-using same media 'C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue'
[libretro INFO] [System] Switched to subimage 0 in 'C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue'
[libretro INFO] [CDROM] Inserting new media, disc region: NTSC-U, console region: NTSC-U
[libretro INFO] [ResetBatchVertexDepth] Resetting batch vertex depth
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [RCHEEVOS]: Awarding achievement 159857: I Have the Power! (Alex has become a Dragonmaster)
[INFO] [RCHEEVOS]: Awarded achievement 159857
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11552976 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11553056 bytes.
[INFO] [RCHEEVOS]: Awarding achievement 161702: Dubious Rubeus (Defeat the Black Dragon without the use of Dragon Spells)
[INFO] [RCHEEVOS]: Awarding achievement 159858: Mad Lizard (Defeat the Black Dragon)
[INFO] [RCHEEVOS]: Awarded achievement 161702
[INFO] [RCHEEVOS]: Awarded achievement 159858
[INFO] [RCHEEVOS]: Awarding achievement 160002: Friendly Memento (Obtain the Rememberizer from Ramus for free)
[INFO] [RCHEEVOS]: Awarded achievement 160002
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11552496 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11552976 bytes.
[INFO] [State]: Saving state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11552496 bytes.
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11552496 bytes.
[libretro INFO] [MemoryCard] Writing memory card sector 63
[INFO] [State]: Loading state "C:\RetroArch-Win64\states\Lunar - Silver Star Story Complete (USA) (Disc 1).state", 11552496 bytes.
[INFO] [State]: Saving state "RAM", 11552496 bytes.
[libretro INFO] [CDROM] Removing CD...
[libretro INFO] [System] Re-using same media 'C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue'
[libretro INFO] [System] Switched to subimage 0 in 'C:\RetroArch-Win64\Roms\Lunar - Silver Star Story Complete (USA) (Disc 1).cue'
[libretro INFO] [CDROM] Inserting new media, disc region: NTSC-U, console region: NTSC-U
[libretro INFO] [ResetBatchVertexDepth] Resetting batch vertex depth
[libretro ERROR] [LUTPageFaultHandler] Loadstore PC not found for 00007FFB01E57E49 in block 0x8009B384

**Comment by DarthMew** [comment]
Try changing "CPU Recompiler Fast Memory Access" from LUT to MMap (if it isn't already), and then try loading your savestate.

**Comment by illcutyouin** [comment]
this indeed fixed my problem thanks so much, out of curiosity was this caused by my new I9 processor?
