### ISSUE TITLE
Manual (no Wifi) Install of Swanstation on a Miyoo Mini

### ISSUE THREAD

**Issue by pocket-books** [libretro/swanstation#28]
I'm having trouble getting Swanstaton to run on a Miyoo Mini with Retroarch running Onion OS.

Would I just need to drop an '.so' file of Swanstation into the Cores folder at -
 MiyooSD_Card/Retroarch/.retroarch/Cores

**Comment by DmitriyFrogo** [comment]
> Would I just need to drop an '.so' file of Swanstation into the Cores folder at - MiyooSD_Card/Retroarch/.retroarch/Cores
>
Yes, but...

While waiting for my own Miyoo Mini, I wanted to find if it compatible with Swanstation core
Prove me wrong, but seems like, there's no any Swanstation cores for ARM processors, for now

https://buildbot.libretro.com/nightly/dingux/miyoo-arm32/latest/

**Comment by pocket-books** [comment]
Nothing there yet, though -
> System Requirements
>     A CPU faster than a potato. But it needs to be x86_64, AArch32/**armv7**, or AArch64/ARMv8, otherwise you won't get a recompiler and it'll be slow.*

*Pulled from the [Swanstation ](https://github.com/libretro/swanstation) Github page

The [Miyoo Mini](https://github.com/TriForceX/MiyooCFW/wiki/Miyoo-Mini) has an [ARM Cortex-A7](https://en.wikipedia.org/wiki/ARM_Cortex-A7) specifically [**this CPU**](https://github.com/linux-chenxing/linux-chenxing.org/blob/master/infinity2/SSD202D_pb_S_v01.pdf).

**Comment by DmitriyFrogo** [comment]
@pocket-books, ARM architecture also used on Android devices, so this part of description is correct

**Comment by pocket-books** [comment]
I see, so just to clarify what we know this far - 
There is general Android compatability for Swanstation at present via the online updater in Retroarch.

While it is possible to run Swanstation on this hardware (Miyoo Mini) there is no Swanstation software configured/packaged to be an obvious 1:1 drop in option.

**Comment by DmitriyFrogo** [comment]
We just need to wait until developers start to build Swanstation for Miyoo and other Dingux devices

**Comment by Cibomatto2002** [comment]
Is this why Swanstation is slow on my Rg-351 because it's not made for Arm processors?

**Comment by pocket-books** [comment]
If the RG-351's Swanstation core is configured with the limited performance of these devices in mind, it could be that they just aren't fast enough.. Though I sort of doubt that's the case with the liberal requirements given by the Swanstation Team.  It's likely they just aren't yet optimized correctly for the lighter end CPUs.

The RG-351 uses a [Cortex A35 Quad Core](https://rockchip.fr/RK3326%20datasheet%20V1.1.pdf) (_datasheet_) inside its [Rockchip RK3326](https://www.cpubenchmark.net/cpu.php?cpu=Rockchip+RK3326) (_benchmark_) board.  It's [ARMv8](https://en.wikipedia.org/wiki/Comparison_of_ARMv8-A_processors), so no worries there.  The Miyoo Mini's [ARMv7](https://en.wikipedia.org/wiki/Comparison_of_ARMv7-A_processors) CPU is an [ARM Cortex-A7 Dual Core](https://www.cpubenchmark.net/cpu.php?cpu=ARM+Cortex-A7+2+Core+1080+MHz&id=4337) (_benchmark_) 

### Anyone out there have information on the processing demands of the Swanstation core?
Information regarding low end benchmarked CPUs of about 150-300 CPU Mark Score running Swanstation would either rule in favor of a future where we could see a Swanstation port to Dingux devices or crush our hopes forever.

The memory demands on the hardware don't appear to be the issue as far as I can tell since there are other cores running the same games just fine.

For comparison's sake the Retroid Pocket 2+ has a [Unisoc Tiger T310](https://www.cpubenchmark.net/cpu.php?cpu=Unisoc+T310&id=4758) (_benchmark_) running at 1.5Ghz.  This processor clocks in with a CPU Mark of 1379 when at 2.0Ghz.
With 1.5Ghz speeds for the mobile power constraints this would drop to about ???
My guess is a lot higher than 150-300

Team Potato, signing out-

**Comment by DmitriyFrogo** [comment]
One of the OnionOS devs said:

> Don't expect duckstation on Miyoo Mini : it requires GPU / hardware acceleration and it is an emulator build for powerful devices. PCSX Rearmed is the best option.

Source:
https://4pda.to/forum/index.php?showtopic=1049150&view=findpost&p=117380216

**Comment by Cibomatto2002** [comment]
Thank you.
