### ISSUE TITLE
Feature Request: Crosshair for lightguns when using mouse

### ISSUE THREAD

**Issue by NatParable** [libretro/swanstation#30]
I'm trying to play a lightgun game using the mouse as a guncon in Retroarch, but I can't see where i'm aiming. Having the option to display a crosshair where the mouse is would be very useful, otherwise lightgun games are unplayable with a mouse.

**Comment by DarthMew** [comment]
The crosshair image doesn't work because of the way it was coded to be part of the upstream frontend, but pressing F11 will make the mouse cursor appear when in game.

**Comment by NatParable** [comment]
Well, turns out my problems go even further than that. When I get to the gun calibration screen in Time Crisis, the game won't register the position of my mouse. It registers the fact that i'm clicking, but it seems to think i'm constantly shooting off screen when i'm not.

**Comment by DarthMew** [comment]
Are you by any change using an aspect ratio other than "corrected"?
If so, changing it to "corrected" should the positioning problem you're describing.

**Comment by NatParable** [comment]
I am already using "corrected".

**Comment by DarthMew** [comment]
Implemented via https://github.com/libretro/swanstation/commit/fb11fcc843a6a883c9bb1c50db3bba4a7ed23108 (currently only for the hardware renderers).
