### ISSUE TITLE
Problem with textures.

### ISSUE THREAD

**Issue by ZzackKbin** [libretro/swanstation#32]
Hello
On swanstation core I have problems with textures:
![](https://i.imgur.com/8Huf4c4.png)
 But on EPSXE 1.6.0 and PCSX Rearmed core all work fine. 
![](https://i.imgur.com/4JZmyKc.png)

Winning Eleven patched from here:
https://youtu.be/oAMwT73dgG0

**Comment by DarthMew** [comment]
I have a few questions:
- What renderers have you tried (Vulkan, OpenGL, DirectX11, Software), and do they produce the same result?
- Are you upscaling the render resolution?
- Does the patch even work correctly on real hardware (the patch might rely on less accurate emulation to function properly, SwanStation is more accurate than either ePSXe or PCSX-ReArmed)?

**Comment by ZzackKbin** [comment]
Strange. In next one even change dx/vulka nothing help.
Software mode:
https://i.imgur.com/Wh8vodd.png

**Comment by ZzackKbin** [comment]
Looks like swanstation have problems with mods in Winning Eleven 2002 images. 
I tested: 
-WE2002(Season 21-22) by SEADOG
-WEOL'15 CT 9.0 

Both work ok on EPSXE 1.6.0 and Rearmed and not correctly on any combination DX/vulkan Swanstation 
Mods for Tekken 3 work ok on Swanstation.

**Comment by DarthMew** [comment]
Again, might be that some of those mods rely on inaccurate emulation, hence why I asked you to if they work on real hardware.
As an alternative, try them with Beetle PSX (software mode, not hardware), and check if the same problem occurs.

**Comment by ZzackKbin** [comment]
beetle can not run any patched iso :)

**Comment by DarthMew** [comment]
Find that very unlikely, but if it cannot run the mods you're trying to run, it's more of a problem with the mods relying on inaccurate emulation rather than it being a problem with SwanStation (or Beetle for that matter).

**Comment by ZzackKbin** [comment]
I think some modes are create for emu and online not for real hardware.

**Comment by DarthMew** [comment]
Then this is not an issue for SwanStation, but for the mod authors to get it to work with more accurate emulators.
