### ISSUE TITLE
[Feature request] Import "Auto (Game Native)" aspect ratio from Duckstation

### ISSUE THREAD

**Issue by Immersion95** [libretro/swanstation#38]
The current "corrected" ratio isn't the same as the "Auto (Game Native)" ratio from Duckstation.

It was present on the old Duckstation core and it gives a proper ratio to all the fighting games. KOF series are slimmer with the "Corrected" ratio while SF series are fatter with the 4/3 ratio.

The "Auto (Game Native)" ratio is perfect with all those games.

**Comment by DarthMew** [comment]
Regardless of what is subjectively a better or more correct aspect ratio, https://github.com/libretro/swanstation/commit/b6a18318bd7bf0d3b28b50d2b554810ea11b30cb re-adds upstreams "game native" as a separate option.
