### ISSUE TITLE
Ronaldo V-Football (Europe) (En,Fr,Nl,Sv)

### ISSUE THREAD

**Issue by darkseekerliu** [libretro/swanstation#39]
Game name: Ronaldo V-Football (Europe) (En,Fr,Nl,Sv)
File type: .bin and .cue files

Description of the problem: game does not boot - retroarch says: "ERROR: System Failed to Boot. The log may contain more information."

There is no log in retroarch's log folder.

Bios files (scph5500.bin / scph5501.bin / scph5502.bin) are on retroarch's system folder. 

Other games do work fine. Tested this game and it only worked fine on epsxe 2.0.5 - 

Cores: PCSX Rearmed and Beetle PSX /HW - boot the game but it gets stuck in the Game Logo after the boot.

**Comment by CometHunter92** [comment]
You need an SBI file for that title.

**Comment by darkseekerliu** [comment]
> You need an SBI file for that title.

Thank you so much. Got sbi file, game running fine.
