### ISSUE TITLE
Revert of the removal of ''Display Internal Framerate'' setting.

### ISSUE THREAD

**Issue by brad86m** [libretro/swanstation#47]
Noticed this morning that the option had been removed. I found it incredibly useful for monitoring games and setting up individual overclocking profiles. I actually requested the feature to be brought over from Beetle PSX, and was happy to when it was implemented here.

If the change for its removal can be reverted, It would be appreciated. Thanks.

**Comment by LibretroAdmin** [comment]
No, I want the entire OSD layer gone. And this feature is not really important or essential for now either.

It might come back later once the OSD layer is gone. For now, it's not important. And the first priority is getting rid of that OSD/frontend subsystem.

**Comment by brad86m** [comment]
Thank you for the response. I understand.

Like you said, it's not essential, but it was nice for monitoring and configuring overclocks for games. If it can return at some point in the future, then awesome.
