### ISSUE TITLE
Please revert the memory card change.

### ISSUE THREAD

**Issue by NatParable** [libretro/swanstation#49]
Those of us who want to use the .MCD format should be able to make that choice for ourselves. Removing the option entirely makes no logical sense.

**Comment by hizzlekizzle** [comment]
I believe it was removed because it was related to savefile corruption. However, there seem to be some other folks who have the opposite issue (that is, corruption with SRM saves that were avoided by using the mcr saves):
https://forums.libretro.com/t/core-and-feature-requests/5895/719

**Comment by DarthMew** [comment]
> Those of us who want to use the .MCD format should be able to make that choice for ourselves. Removing the option entirely makes no logical sense.

Well, if you say so.
Anyway, reverted.
