### ISSUE TITLE
Naming Memory Cards

### ISSUE THREAD

**Issue by MortalisJhen** [libretro/swanstation#5]
Hello, I have it set to save Memory Card per Game Name, so like Xenogears_1.mcd or Xenogears_2.mcd.

I also have it set up to sync with Dropbox and I play on my phone or windows PC so I can pick up where I left off.

On Android though it names it "_storage_emulated_0_RetroArch_roms_Sony Playstation_Xenogears_1.mcd" so now each OS cannot see the card. Is there a way to not have the filepath on Android? I tried the Libretro SRAM option but was having issues.

I tried the Game Code or Shared Mem Card option and they work, those do not add the filepath on Android, just wondering if it is possible to do that with the Game Name option as well. Thank you.

**Comment by DarthMew** [comment]
I've looked into it before, but there doesn't seem to be anything obvious in the code that would cause this, other than perhaps the hard codes _1 and _2 additions.

But you mentioned that you were having issues with the Libretro SRAM option.
Could you describe what exactly the issue is you're having with that (seeing as it is the default memory card option for Swanstation).

**Comment by MortalisJhen** [comment]
I have had it delete my saves when loading a state, like loading a state that was earlier than a save would wipe the card. I think Retroarch has a option to not overwrite SRAM when loading a state but I don't think that has helped, Swanstation always just says it needs to simulate replugging and there goes my saves. Using the mcd options I have not had that issue.

**Comment by DarthMew** [comment]
You have "Load Devices From Save States" enabled?

**Comment by MortalisJhen** [comment]
That is currently off.

**Comment by DarthMew** [comment]
Tried it out myself with Bust-A-Move 4 and Crash 3 with it off, and my saves remain intact after loading a pre-save state (after it simulates a replug that is).

Regardless of that, have you tried with the option enabled?
