### ISSUE TITLE
Feature Request: Mouse support (Right stick to mouse)

### ISSUE THREAD

**Issue by UserGit-2021** [libretro/swanstation#51]
Right stick emulation mouse support

**Comment by crashGG** [comment]
Many FPS games on ps1 do not support the right joystick. If want to achieve keyboard + mouse operation like games on pc, such as CS, then need to map the direction of the mouse independently for each joy button.

**Comment by UserGit-2021** [comment]
> Many FPS games on ps1 do not support the right joystick. If want to achieve keyboard + mouse operation like games on pc, such as CS, then need to map the direction of the mouse independently for each joy button.

https://drive.google.com/file/d/140HjFlqkSLejpvX7vfx3JQ63kURUyQMp/view?usp=share_link

Why did the Duckstation emulator add right stick emulation to the mouse? They succeeded.

**Comment by DarthMew** [comment]
Closing this because AFAIK, you can't map mouse axis to controller inputs in RetroArch, and is more suited as a frontend feature request.
