### ISSUE TITLE
Mac OS ARM: Vsync doesn't work

### ISSUE THREAD

**Issue by personaone** [libretro/swanstation#56]
Hey - first of all, just wanted to say thanks for the ARM build! I started to test it right after it appeared :) Only thing that I noticed so far, is that Vsync doesn't seem to be working? Even forced to 60hz, it doesn't apply and there's pretty bad frame pacing all over and interlaced screens just shake in this weird way they don't on other cores. Here's a log from the core, maybe it helps?

I'm on a 2021 MacBook Pro with M1 Pro and the latest build of RA/Swanstation core. Tried with both, ProMotion enabled and syncing to content and without using manually set 60hz in the system.

https://pastebin.com/0GC7ebSm

**Comment by personaone** [comment]
False positive - looks like the new RA build set GLcore as the default Mac OS driver, Metal works just as it should.

**Comment by LibretroAdmin** [comment]
I think a better alternative could be the Vulkan driver now with Vulkan/MoltenVK.

**Comment by personaone** [comment]
> I think a better alternative could be the Vulkan driver now with Vulkan/MoltenVK.

Vulkan does run very well too - I just realized it's there now too :D again, ProMotion @120hz doesn't seem to engage VRR when trying to sync to content, but 60hz fixed refresh rate is way to go around that problem :)
