### ISSUE TITLE
Issue using dots in core configuration file

### ISSUE THREAD

**Issue by rtomasa** [libretro/swanstation#61]
Hi,

I noticed the core uses a non standard way to define configuration parameters like `duckstation_BIOS.PatchFastBoot = "true"`
The use of dots in the keys prevents using libraries like _libconfig_ from reading these files since they only support underscores.

Would be possible to change dots to underscores for future releases?

**Comment by DarthMew** [comment]
I certainly wouldn't have a problem with changing it, but the problem with changing it would be that it completely reset everyones SwanStation configurations, and I'm pretty sure no one will appreciate that happening to them.

**Comment by rtomasa** [comment]
Do you really think that many people will complain on changing the same? I mean, the worst thing that could happen is that RetroArch would recreate the new named options with default values. The trade-off is ease the use of other potential frontends and external tools.
From development perspective, creating a parser for key=value it's not very hard to do, but forcing to reinvent the wheel for already existing C libraries like libconfig because of this issue is a real pain specially if you were trying to use more sophisticated things like categories, etc.

**Comment by DarthMew** [comment]
You might be surprised by how many people would start to complain when they notice that, after an update, suddenly all their personally configured settings have been reset.

Anyway, I'm going to ask and see what @LibretroAdmin thinks of this, and if this is something that should be proceeded with.

EDIT: I've been told it's fine as a one time only change.

**Comment by rtomasa** [comment]
Thanks. It is not an stopper or something super critical but certainly annoying from dev perspective.

**Comment by DarthMew** [comment]
Implemented via https://github.com/libretro/swanstation/pull/62
