### ISSUE TITLE
[RPi4, GLES] Cannot use HW renderer when PGXP Texture Correction is turned on

### ISSUE THREAD

**Issue by ectorhga** [libretro/swanstation#64]
Hi,
I'm using Swanstation on a Raspberry Pi 4 (Buster, 32bit, 2GB RAM, KMS driver enabled) compiled from the master branch with HW GLES renderer. 

I have noticed, that I get an error when I start Swanstation with "PGXP Texture Correction" turned on (see [verbose log](https://pastebin.com/8P45ewd5)). The error message that pop up is "Failed to initialize OpenGL renderer, falling back to software renderer". I can start Swanstation in HW renderer mode without the texture correction and enable it afterwards, but I'm not sure, if it works or not.

Here are my [Swanstation core options](https://pastebin.com/g9MiKGTM), if that helps.

**Comment by DarthMew** [comment]
Could you please check if it still happens with the latest [update.](https://github.com/libretro/swanstation/commit/e24f21196cdcd50321475c4366b51af245a6bbe6)

**Comment by ectorhga** [comment]
It's fine now, thanks a lot! 
Just out of curiosity, as I I don't really understand what you changed: is the Texture Correction not working with GLES or was there a different problem?

**Comment by DarthMew** [comment]
It had to do with non-perspective colors not being properly supported on GLES.
