### ISSUE TITLE
Swanstation core dont save setting in the core option

### ISSUE THREAD

**Issue by OldGamers** [libretro/swanstation#65]
I had tried so many times to save the setting for the swan station's core option won't save no matter what i do.
don't work on the main save of retro arch or try to save on the new save config and nothing works. 
every time I run swan station its force all the games in windows modes never on full screen, just nothing is working.

**Comment by DarthMew** [comment]
Don't try to save core options as core overwrites.

**Comment by OldGamers** [comment]
> Don't try to save core options as core overwrites.
where do i go to save ?

**Comment by DarthMew** [comment]
`Core Options > Manage Core Options > Flush Options to Disk` To make absolutely sure it saves the changed core options (shouldn't be necessary as RetroArch already saves core options to config when exiting a game, but just in case).
Also, make sure you don't have any lingering core overrides by going to your RetroArch install directory, enter `config/swanstation` and remove any file that has a .cfg extension.

**Comment by OldGamers** [comment]
thank you that fix the issue :)
