### ISSUE TITLE
Rquest: Rumble in NeGcon mode

### ISSUE THREAD

**Issue by sonik-br** [libretro/swanstation#67]
Some games supports negcon mode with rumble.
Some devices uses the negcon protocol to transmit data and also supports receiving commands (like a dualshock does)

Can this feature be added?

Example of games with this feature:

Arkanoid R 2000.
Supports rumble in analog or negcon mode.
In-game pause screen shows rumble options when the device supports rumble.
Rumble type2 is interesting to test as it will use left or right motor if the ball hits the left or right wall.

Side by Side Special 2000
Rumble will be used if supported by device. Defaults to enable.

**Comment by DarthMew** [comment]
Implemented via https://github.com/libretro/swanstation/commit/83776ae7d3b9221b2746f91af0c2d8d9b0994aa7
