### ISSUE TITLE
Add cheat codes in duckstation cht format [feature request]

### ISSUE THREAD

**Issue by crashGG** [libretro/swanstation#68]
read cheat codes in cht format in the directory
\cheats\GAME.cht

Examples of content are:

#group=Ungrouped
#type=Gameshark
#activation=EndFrame
[Widescreen 16-9]
80017A4C 0C00
80017A4E 2402
80017A8E A433

**Comment by DarthMew** [comment]
Cheat file loading and management is a thing that's handled by the frontend, not the core.

If you want to easily convert it to RetroArch format, you can use this (not tested it myself, but it should be fine from the looks of it):
https://gbatemp.net/threads/release-retroarch-cheat-creator.615062/
