### ISSUE TITLE
Fix up ps1 games stutters on Android tv

### ISSUE THREAD

**Issue by Jackmath5** [libretro/swanstation#7]
Can you fix up ps1 games for Android slowing them down and stutters?

**Comment by DarthMew** [comment]
I have a few questions.

- What are the settings you're using for Swanstation and RetroArch?
- What is the exact Android TV hardware you're using?
- Would you happen to have RetroArch's rewind on by any change (Swanstation is incompatible with it and relies on its own implementation)?
- Did this always happen, or did it happen after an update for Android TV, RetroArch, or core?
- What format is your game using (bin+cue, chd, pbp etc.)?

**Comment by Jackmath5** [comment]
https://github.com/libretro/beetle-saturn-libretro/issues/218

**Comment by Jackmath5** [comment]
> I have a few questions.
> 
> * What are the settings you're using for Swanstation and RetroArch?
> * What is the exact Android TV hardware you're using?
> * Would you happen to have RetroArch's rewind on by any change (Swanstation is incompatible with it and relies on its own implementation)?
> * Did this always happen, or did it happen after an update for Android TV, RetroArch, or core?
> * What format is your game using (bin+cue, chd, pbp etc.)?

Idk.

https://github.com/libretro/beetle-saturn-libretro/issues/218
