### ISSUE TITLE
Rumble not available in swanstation core

### ISSUE THREAD

**Issue by ghiki** [libretro/swanstation#70]
The Rumble effect doesnt work in swanstation core, but It works perfectly un duckstation standalone. The idea is to work with internal android vibrators (the device si a Retroid pocket3+)

**Comment by Immersion95** [comment]
It works.
Controls-->Port 1-->Dualshock
Save the Core Remap File then.

You can close the issue :)

**Comment by DarthMew** [comment]
Solution has been provided, closing.
