### ISSUE TITLE
Formula 1 Championship Edition freezes Retroarch

### ISSUE THREAD

**Issue by Denshadego** [libretro/swanstation#73]
As the title says, Formula 1 Championship Edition (NTSC-U) freezes Retroarch when trying to load the ingame portion. For example, when trying to start a race, the screen goes black and the application freezes.

Tested with default core options, happens both in Software and Hardware modes, and both in Windows 10 and Android.

**Comment by DarthMew** [comment]
Reverting https://github.com/libretro/swanstation/commit/0d46e464d2b898123dc0fc8f182d64fb52b50314 allows the game to go past the menus and into a race.
@realnc would you mind looking into it and see what could possibly cause this?

**Comment by DarthMew** [comment]
https://github.com/libretro/swanstation/commit/39c86ae8e5c48dd6775da6127d97f771d29221d9
Went ahead and moved the code back to FramesAvailable, allowing the game to boot again.

**Comment by DarthMew** [comment]
https://github.com/libretro/swanstation/commit/afb6bc73c7ce522190b19ec3e3c8a14eb264bdeb reintroduces the hang, but you'll be able to bypass it by disabling the "Use Alternative Audio Hook" option located in the advanced tab of the core options.
