### ISSUE TITLE
[Bug]Analog mode combo needs a delay option like Beetle

### ISSUE THREAD

**Issue by Immersion95** [libretro/swanstation#77]
When doing the combo for the analog mode, it is changing with the speed of light.

**Comment by DarthMew** [comment]
I've looked into this before, but the toggle works fine on my end using a regular set of controllers on Windows (Xbox, DualShock, Dualsense etc.) without it rapid firing (as previously discussed in https://github.com/libretro/swanstation/issues/4), so I'm closing this until someone can precisely identify why this happens to some people in the first place.

As for a hold delay for the toggle, I'm not going to look into it myself, but a PR implementing it is always welcome.

**Comment by Immersion95** [comment]
Found the culprit and how to reproduce it on your end.
When you choose Analog controller for :
Port 1 only -->OK
Port 1 + Port 2 or 3 or whatever -->Rapid fire

If that is solved, the delay won't be needed of course :).

**Comment by DarthMew** [comment]
Thank you for pinpointing it.
Now to figure out how to block the rapid firing.

**Comment by DarthMew** [comment]
https://github.com/libretro/swanstation/commit/9a88828f8bb7d4db891ff3101bfa7eaac3197995 should fix it.
