### ISSUE TITLE
Choppy sound and image on Metal Gear Solid PAL [Pi4]

### ISSUE THREAD

**Issue by toniosj** [libretro/swanstation#8]
Metal Gear Solid PAL runs very laggy with choppy sound on Raspberry Pi4.

**Comment by DarthMew** [comment]
I have a few questions.

- What are the settings you're using for Swanstation and RetroArch (or equivalent Libretro compatible frontend)?
- Does the choppy sound and image happen with other PS1 games, PAL or otherwise?
- Would you happen to have RetroArch's rewind on by any change (Swanstation is incompatible with it and relies on its own implementation)?
- Did the game always run badly, or did it happen after an update for the Pi4, frontend, or core?
- What format is your game using (bin+cue, chd, pbp etc.)?

**Comment by toniosj** [comment]
Hi! 

- What are the settings you're using for Swanstation and RetroArch (or equivalent Libretro compatible frontend)?

> I'm using Recalbox

- Does the choppy sound and image happen with other PS1 games, PAL or otherwise?

> Metal Gear Solid (PAL)
> Metal Gear Solid (NTSC)
> Crash Team Racing (PAL)
> Crash Team Racing (NTSC)
> Norse by Norsewest: The Lost Vikings 2 (PAL)
> Norse by Norsewest: The Lost Vikings 2 (NTSC) https://forums.libretro.com/t/swanstation-what-causes-norse-by-norsewest-to-be-so-slow/36413

- Would you happen to have RetroArch's rewind on by any change (Swanstation is incompatible with it and relies on its own implementation)?

> Rewind : Disabled

- Did the game always run badly, or did it happen after an update for the Pi4, frontend, or core?

> Always 

- What format is your game using (bin+cue, chd, pbp etc.)?

> bin+cue(+sbi)

**Comment by DarthMew** [comment]
What I was asking with my first question was more about what your core and frontend settings were, like renderer, enhancements and etc.

Regardless of that, could you try the following:
- Check if either the software renderer, or and of the available hardware renderers affect performance.
- In Swanstation's Display Settings tab, change Crop Mode from "All Borders" to either "Only Overscan Area" or "None" and/or change Core Provided Aspect Ratio from "Auto (Game Native)" to something like "4:3".
- Make sure you haven't enabled any enhancements like higher resolution scale or PGXP.

**Comment by toniosj** [comment]
All PGXP options disabled.
Crop Mode = None
Renderer = Sofware and Hardware tested (with hardware, games that worked prefectly on software have got poor performance, so I use Software)

New games detected that don't work fine:

Suikoden (PAL)
Porsche Challenge (PAL): Sound starts to choppy when race start.

**Comment by DarthMew** [comment]
And it also doesn't matter if you use either OpenGL or Vulkan for the hardware renderer?

I'm afraid I personally can't be more of assistance, as I don't own a Pi4 myself, so it might be a good idea to ask other people who also use Swanstation on a Pi4 what their experience is so a clearer picture can be drawn regarding this issue.

**Comment by ghost** [comment]
I believe the pulse audio that recalbox has as default on the retroarch, affect the performance of swanstation. If you set it to alsathread, games running fast but, without audio.

From my tests, i have the best performance of swanstation with software renderer and alsathread.

**Comment by toniosj** [comment]
Cool!
I've tried a Recalbox beta with alsathread and now these games are working at fullspeed and they have got audio!!!!!

Metal Gear Solid (PAL)
Metal Gear Solid (NTSC)
Crash Team Racing (PAL)
Norse by Norsewest: The Lost Vikings 2 (PAL)
Suikoden (PAL)
Porsche Challenge (PAL) 

Looks like a Swanstation compatibility issue with the PULSE audio driver.

**Comment by digitalLumberjack** [comment]
Hello :)

Thank you for all the work on this core !

I was also testing retroarch + swanstation with MGS Pal version on recalbox, and the pulseaudio thread use like 130% of the cpus on rpi4.
Having aslathread as default driver do the trick and we will implement it in recalbox, but as it's the only core in all cores and emulators in recalbox having this issue, it was worth reporting it @toniosj :pray:
