### ISSUE TITLE
Steam Deck Metal Gear Solid stuttering

### ISSUE THREAD

**Issue by benpdavis** [libretro/swanstation#80]
I am getting stuttering in Metal Gear Solid when using pulse/alsa audio on the Steam Deck.

I am fairly confident that this was working/I had not previously changed the audio settings at all so not sure if this is because the default audio used by RetroArch has changed in an update and this was a prexisting issue or an update of either the Steam Deck or SwanStation may have introduced this.

 Switching the audio driver to alsathread and restarting SwanStation gets rid of the stuttering.

I have seen some talk online about it being linked to the fps/refresh rate limiting but so far changing this setting does not appear to have any impact.

Edit: same stuttering in Metal Gear Solid - VR Missions but all other games are fine so far.

Edit edit: after some messing around where I occasionally had it launch without the stuttering but a hard reboot always led to stuttering. Restoring the only backup I have (1.0.0 8f6feca) for the core gets rid of the issue and then updating again (1.0.0 39c86ae)brings it back.

**Comment by DarthMew** [comment]
https://github.com/libretro/swanstation/commit/afb6bc73c7ce522190b19ec3e3c8a14eb264bdeb may fix this.

**Comment by benpdavis** [comment]
I have just updated and loaded it up and the stuttering is gone from the intro cutscene so looking good!
