### ISSUE TITLE
Castlevania Chronicles freezes on title screen

### ISSUE THREAD

**Issue by ghost** [libretro/swanstation#82]
Castlevania Chronicles freezes on title screen. It works perfectly on duckstation and beetle psx

retroarch FORCED me to update to swanstation and deleted my duckstation core giving me absolutely no choice! when I was more than happy with duckstation and every game I tried was working perfectly! now I have to use beetle psx to play Castlevania Chronicles!!

**Comment by NovAProspekT-96** [comment]
Now having this problem with several games after updating to 3767447. Several games cause the app to crash every 5 seconds or so and bring up a window saying "RetroArch isn't responding".

**Comment by ghost** [comment]
> Now having this problem with several games after updating to [3767447](https://github.com/libretro/swanstation/commit/376744746a6880b5eec7ac48b5c006c9ae8c6770). Several games cause the app to crash every 5 seconds or so and bring up a window saying "RetroArch isn't responding".

this has absolutely nothing to do with the issue I get, you should post your own issue

**Comment by JBHenson** [comment]
Also freezes on Twinbee Yahho and Harmful Park (the latter might be a bad rip on my end though)

**Comment by KamiLordus** [comment]
Same problem with Castlevania Chronicles. The game freezes at the title screen. It was working without a problem before.
CHD image
software rendering
default settings for the core
Retroarch 1.16
Swanstation latest
Win 11.

**Comment by ThatGeoDude** [comment]
> Same problem with Castlevania Chronicles. The game freezes at the title screen. It was working without a problem before. CHD image software rendering default settings for the core Retroarch 1.16 Swanstation latest Win 11.

I was having the same problem. I deleted the CHD image and instead used the CUE and it worked. Something funky happened when they updated Retro and the compression of the CHD. Noticed that the crash happened as soon the menu music tried to play.

**Comment by KamiLordus** [comment]
In my case, the game image format doesn't matter. I have the same problem with cue format.

**Comment by DarthMew** [comment]
Fixed with https://github.com/libretro/swanstation/commit/f88d108cb3982115dfff10905a8c2ab53676269a
