### ISSUE TITLE
Medal of Honor 1 and 2 broken music 

### ISSUE THREAD

**Issue by KamiLordus** [libretro/swanstation#90]
Medal of Honor 1 and 2 have completely broken in-game music.
RA 1.16
Win 11
CHD game image
I think this is the same problem described here:
https://github.com/libretro/swanstation/issues/82
Before the afb6bc7 update, both games worked without any problems.
@DarthMew can you check it, or restore the swanstation version before afb6bc7? Because this patch breaks more than it fixes.

**Comment by DarthMew** [comment]
Have you even tried to toggle the option?

**Comment by KamiLordus** [comment]
I tested option "use alternative audio hook on/off". 
But it doesn't change anything for MoH 1 and 2 and Castlevania Chronicles.

edit:
The games are in NTSC USA format.
In addition to chd images, I also tested bin/cue images - same problem.
I leave the retroarch log from turning Medal of Honor 1 on and off
[retroarch.log](https://github.com/libretro/swanstation/files/13071279/retroarch.log)

**Comment by KamiLordus** [comment]
After extensive testing, I managed to determine the problem.
The described problem occurs when the game is running with the auto-detect "Console region" setting. The same thing happens when we set NTSC (USA, Canada).
However, both parts of MoH in NTSC format (USA) work properly when the "Console region" is set to PAL (Europe, Australia).

**Comment by DarthMew** [comment]
Very likely fixed with https://github.com/libretro/swanstation/commit/f88d108cb3982115dfff10905a8c2ab53676269a

**Comment by KamiLordus** [comment]
Thank you very much. Now it works without any problem.
