### ISSUE TITLE
vib-ribbon japanese ntsc and eu pal not working

### ISSUE THREAD

**Issue by gabberhead** [libretro/swanstation#93]
i try to play the game today. the game starts fine. with the pal version i can chose the language and then on the next sreen i choose game, and then appears the loading screen and there it hangs. when i chose "how to play", this works. when chosing how to play the loading screen also appears, but the stars are spinning left and right at "loading". when trying to start the game, there are no spinng stars left and right at "loading". same problem exists also with the japanese version. i tried everything, but i can not get it to work. with beetle psx HW core the game works fine. tried with cue/bin and chd files.

**Comment by gabberhead** [comment]
i found an older core from 24.6.2023 with that core, the game now works fine. testet with chd file. so there is nothing wrong with the config for the game. it loos like, there is something wrong with the core.

**Comment by KamiLordus** [comment]
Seems to be the same problem as Castlevania Chronicles. Definitely, one of the recent swanstatnion updates broke something.
Where can you find retroarch archive cores?

**Comment by gabberhead** [comment]
i had a backup of my complete retroarch folder from june.

**Comment by KamiLordus** [comment]
Swanstation is only about 3 MB, if it's not a problem, zip it with winrar and post it here. I will be grateful because I can't find such a version anywhere and the current one is a nightmare - only problems and broken games.

**Comment by gabberhead** [comment]
[swanstation_libretro.zip](https://github.com/libretro/swanstation/files/13301856/swanstation_libretro.zip)

**Comment by KamiLordus** [comment]
Great, thank you very much.

**Comment by DarthMew** [comment]
Next time anyone wants an older core, go to the Libretro buildbot and download it from there.

Anyway, fixed with https://github.com/libretro/swanstation/commit/f88d108cb3982115dfff10905a8c2ab53676269a
