### ISSUE TITLE
Formula 1 97 - NTSC Japan & USA Versions are freezeing after the menu. Europe PAL Version is working

### ISSUE THREAD

**Issue by gabberhead** [libretro/swanstation#94]
I have tested those 3 versions. the only one which is working, is the europe pal release. all 3 versions are starting fine till the menu, but when u try to get in the game after the menu, both ntsc versions are freezing. the pal version loads fine into the game after the menu. tested with cue/bin & chd.

PS. first i thought it  is the same problem like vib-ribbon, but vib-ribbon is now laoding without problems after it was fixed.

**Comment by DarthMew** [comment]
Dupe of https://github.com/libretro/swanstation/issues/73
Turn off the "Use Alternative Audio Hook" option located in the advanced tab of the core options.
